[build]
target = "x86_64-kalesh_os.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-kalesh_os]
linker = "ld.lld"
rustflags = ["-C", "link-arg=-Tlinker.ld"]


